### PR TITLE
some tiny fixes when playing with scoutfs

### PR DESCRIPTION
**Pull request by wangshilong1991**
Hi Zach,

   Follwing are some tiny fixes that when i try to play with scoutfs...

### CODE REVIEW

**Comment by benmcclelland** [comment]
Thanks for the contributions!  Some feedback on the server_addr patch:
We are intending for this to be optional.  The server_addr mount option is only required for mounts that will be participating in quorum election.  Mounts without the server_addr option will just wait until a leader is elected and then connect.  This should add overall scalability to the size of the scoutfs cluster to limit the size of the quorum participants.

**Comment by wangshilong1991** [comment]
Thanks for feedback, this makes sense for me.

**Review by KnightKu — APPROVED** [review]

**Review by zabbo — APPROVED** [review]
This great, thanks for taking the time to fix my silly typos.  I've merged this along with a branch that fixed the interrupted lock destruction assertion.

**Review by zabbo — CHANGES_REQUESTED** [review]
This isn't quite right.  The lock request can still be pending if the original submitter left after having been interrupted.  The lock change will still happen.  What's breaking here is shutdown thinking that a request is still in flight after networking has been shutdown.  I merged a more precise fix in another branch, thanks for working on this!

**Comment by zabbo** [comment]
Sorry for the delay, I was distracted by moving house :).  I've cherry picked your README fix and merged a more accurate fix for the bug_on assertion during lock shutdown, along with a test.  Thanks for taking the time to submit the fixes!

**Pull request closed without merging**
